In [20]:
from sklearn import datasets
breast_cancer = datasets.load_breast_cancer()
print(breast_cancer.filename)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\datasets\data\breast_cancer.csv


In [19]:
from sklearn import datasets
breast_cancer = datasets.load_breast_cancer()
print(breast_cancer.filename)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\datasets\data\breast_cancer.csv


In [13]:
import numpy as np
breast_cancer_data = np.genfromtxt('C:\\Users\\asus\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\breast_cancer.csv',
                                  delimiter=",", skip_header=1)
print(breast_cancer_data)

[[1.799e+01 1.038e+01 1.228e+02 ... 4.601e-01 1.189e-01 0.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 ... 2.750e-01 8.902e-02 0.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 ... 3.613e-01 8.758e-02 0.000e+00]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 2.218e-01 7.820e-02 0.000e+00]
 [2.060e+01 2.933e+01 1.401e+02 ... 4.087e-01 1.240e-01 0.000e+00]
 [7.760e+00 2.454e+01 4.792e+01 ... 2.871e-01 7.039e-02 1.000e+00]]


In [17]:
import numpy as np
breast_cancer_data = np.genfromtxt('C:\\Users\\asus\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\breast_cancer.csv',
                                  delimiter=",", skip_header=1)
print("mean of {} is {}".format(breast_cancer.feature_names[1], breast_cancer_data[:,1].mean()))

mean of mean texture is 19.289648506151142
